version: '3.8'
services:
  http:
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
      args:
        package_name: tcp_dummy_services
    command:
      [
        "uvicorn",
        "tcp_dummy_services.http.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
    ports:
      - 8000:8000
    environment:
      - LOG_LEVEL=DEBUG
      - LOGGER_NAME=tcp-dummy-services
      - STUFF_ENABLED=false

  ws:
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
      args:
        package_name: tcp_dummy_services
    command:
      [
        "uvicorn",
        "tcp_dummy_services.ws.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8001"
      ]
    ports:
      - 8001:8001
    environment:
      - LOG_LEVEL=DEBUG
      - LOGGER_NAME=tcp-dummy-services

  remote_http:
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
      args:
        package_name: tcp_dummy_services
    command:
      [
        "uvicorn",
        "tcp_dummy_services.http.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8002"
      ]
    ports:
      - 8002:8002
    environment:
      - LOG_LEVEL=DEBUG
      - LOGGER_NAME=tcp-dummy-services
      - STUFF_ENABLED=true
      - THINGS_ENABLED=false
      - THINGS_BASE_URL=http://http:8000

  tcp:
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
      args:
        package_name: tcp_dummy_services
    command:
      [
        "python",
        "/code/tcp_dummy_services/tcp/"
      ]
    ports:
      - 7001:7001
      - 7002:7002
      - 7003:7003
    environment:
      - LOG_LEVEL=DEBUG
      - LOGGER_NAME=tcp-dummy-services
      - TCP_PORTS=7001-7003

networks:
  app-network:
    driver: bridge
