version: '3.8'
services:
  http:
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
      args:
        package_name: tcp_dummy_services
    command:
      [
        "sh",
        "-c",
        "uvicorn tcp_dummy_services.http.main:app --host 0.0.0.0 --port 8000"
      ]
    ports:
      - 8000:8000
    environment:
      - LOG_LEVEL=DEBUG
      - LOGGER_NAME=tcp-dummy-services

  ws:
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
      args:
        package_name: tcp_dummy_services
    command:
      [
        "sh",
        "-c",
        "uvicorn tcp_dummy_services.ws.main:app --host 0.0.0.0 --port 8001"
      ]
    ports:
      - 8001:8001
    environment:
      - LOG_LEVEL=DEBUG
      - LOGGER_NAME=tcp-dummy-services

  tcp:
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
      args:
        package_name: tcp_dummy_services
    command: [ "sh", "-c", "/code/tcp.sh" ]
    ports:
      - 7001:7001
      - 7002:7002
      - 7003:7003
    environment:
      - LOG_LEVEL=DEBUG
      - LOGGER_NAME=tcp-dummy-services
      - TCP_PORTS=7001-7003

networks:
  app-network:
    driver: bridge
